# ===== Hyperparameters =====
input_size: 10 # must be equal to time_step for LSTM
hidden_layers: [100, 100, 100, 100, 100]
output_size: 1 # must be 1 for LSTM
learning_rate: 0.0001
epochs: 100
test_size: 0.2
# for LSTM
time_step: 10 
batch_size: 16